dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.1.0
  - smartcontractkit/chainlink-brownie-contracts@1.2.0


compiler:
  solc:
    remappings:
      - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.1.0"
      - "@chainlink=smartcontractkit/chainlink-brownie-contracts@1.2.0"